apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "webapp-python-beta.fullname" . }}-beta
  namespace: {{ .Values.namespace }}
data:
  my_secret_value: {{ "very-secret-beta-1" | b64enc }}
