apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "webapp-python-alpha.fullname" . }}-alpha
  namespace: {{ .Values.namespace }}
data:
  my_secret_value: {{ "very-secret-alpha-3" | b64enc }}
